import { JSX } from "react";

export const Faqs = (): JSX.Element => {
  return (
    <div className="fraqs">
      <p className="textLG">FAQs</p>

      <span>
        <p className="title">What is Reorg DAO ?</p>
        <p className="desc">
     Reorg DAO is a decentralized autonomous organization focused on
          supporting web3 products, including DApps, protocols, and other web3
          technologies. Our platform connects startups with a community of
          investors, providing a transparent and efficient funding mechanism
          through tokenization and decentralized governance.
        </p>
      </span>

      <span>
        <p className="title">How does Reorg work ?</p>
        <p className="desc">
      Startups apply to have their projects tokenized on the Reorg platform.
          We partner with experts to evaluate the viability of each project.
          Approved startups undergo tokenization, and our AI model recommends an
          optimal tokenomics structure. Investors in the DAO pool their funds
          to invest in these projects, participate in governance, and share in
          the revenue generated by the startups.
        </p>
      </span>

      <span>
        <p className="title">What is the role of the DAO in Reorg?</p>
        <p className="desc">
      Startups can apply on the Reorg platform, where they will undergo a
          viability check by our partners. Once approved, they fill in a form
          for token details, and the token is created and launched on the
          platform. Investors then vet and vote on the project within the DAO.
        </p>
      </span>

      <span>
        <p className="title">How can a startup apply for tokenization on Reorg?</p>
        <p className="desc">
      Startups can apply on the Reorg platform, where they will undergo a
          viability check by our partners. Once approved, they fill in a form
          for token details, and the token is created and launched on the
          platform. Investors then vet and vote on the project within the DAO.
        </p>
      </span>

      <span>
        <p className="title">
 What are the benefits of tokenizing a startup on Reorg?
        </p>
        <p className="desc">
          Tokenizing a startup on Reorg allows for efficient fundraising from a
          global pool of investors. It provides transparent and democratic
          governance through the DAO, ensures liquidity through token
          transactions, and leverages AI-driven insights for optimal tokenomics.
        </p>
      </span>

      <span>
        <p className="title">
What is the Reorg Token?
        </p>
        <p className="desc">
         The Reorg token is the native token of our platform, used for applying
          for tokenization, participating in DAO governance, and facilitating
          transactions. It can be traded on supported exchanges and is integral
          to the platform's ecosystem.
        </p>
      </span>

      <span>
        <p className="title">
    What rights do I get as an investor?
        </p>
        <p className="desc">
   As an investor, you join the Reorg DAO and gain voting rights on key
          decisions affecting the startups you invest in. This allows you to
          have a direct impact on governance, strategic direction, and
          participation in revenue sharing.
        </p>
      </span>

     
    </div>
  );
};
