// Mock data for assets associated with each token
export const MockAssets = [
    // Assets for Cyber Token (CYQ)
    {
      id: 1,
      project: "CyberQuest",
      name: "Quantum Shield",
      price: 0.5,
      image: "https://via.placeholder.com/150/0000FF/808080?text=Quantum+Shield",
      category: "Armor",
      featured: true,
      description: "A shield that protects against quantum attacks.",

    },
    {
      id: 2,
      project: "CyberQuest",
      name: "Photon Blade",
      price: 0.7,
      image: "https://via.placeholder.com/150/0000FF/808080?text=Photon+Blade",
      category: "Weapon",
      featured: false,
      description: "A sword that deals massive photon damage.",
    },
    {
      id: 3,
      project: "CyberQuest",
      name: "Neural Interface",
      price: 1.2,
      image: "https://via.placeholder.com/150/0000FF/808080?text=Neural+Interface",
      category: "Accessory",
      featured: true,
      description: "A device that enhances your neural connections.",
    },
    
    // Assets for Dragon Coin (DSK)
    {
      id: 4,
      project: "DragonStrike",
      name: "Flaming Sword",
      price: 0.8,
      image: "https://via.placeholder.com/150/808000/808080?text=Flaming+Sword",
      category: "Weapon",
      featured: true,
      description: "A sword that deals massive fire damage.",
    },
    {
      id: 5,
      project: "DragonStrike",
      name: "Dragon Scale Armor",
      price: 1.5,
      image: "https://via.placeholder.com/150/808000/808080?text=Dragon+Scale+Armor",
      category: "Armor",
      featured: false,
      description: "A set of armor that provides excellent protection.",
    },
    {
      id: 6,
      project: "DragonStrike",
      name: "Healing Potion",
      price: 0.3,
      image: "https://via.placeholder.com/150/808000/808080?text=Healing+Potion",
      category: "Consumable",
      featured: false,
      description: "A potion that restores health.",
    },
    
    // Assets for Galaxy Token (GRT)
    {
      id: 7,
      project: "GalaxyRaiders",
      name: "Plasma Cannon",
      price: 1.0,
      image: "https://via.placeholder.com/150/00FF00/808080?text=Plasma+Cannon",
      category: "Weapon",
      featured: true,
      description: "A powerful cannon that deals massive energy damage.",
    },
    {
      id: 8,
      project: "GalaxyRaiders",
      name: "Starship Hull",
      price: 1.8,
      image: "https://via.placeholder.com/150/00FF00/808080?text=Starship+Hull",
      category: "Armor",
      featured: true,
      description: "A hull that provides excellent protection for your starship.",
    },
    {
      id: 9,
      project: "GalaxyRaiders",
      name: "Cosmic Gem",
      price: 0.5,
      image: "https://via.placeholder.com/150/00FF00/808080?text=Cosmic+Gem",
      category: "Collectible",
      featured: false,
      description: "A rare gem that grants unique abilities.",
    },
  
    // Assets for Solar Coin (SLC)
    {
      id: 10,
      project: "SolarConquest",
      name: "Solar Flare Staff",
      price: 0.9,
      image: "https://via.placeholder.com/150/000FF/808080?text=Solar+Flare+Staff",
      category: "Weapon",
      featured: true,
      description: "A staff that unleashes powerful solar flares.",
    },
    {
      id: 11,
      project: "SolarConquest",
      name: "Radiant Shield",
      price: 0.6,
      image: "https://via.placeholder.com/150/000FF/808080?text=Radiant+Shield",
      category: "Armor",
      featured: false,
      description: "A shield that absorbs and reflects energy attacks.",
    },
    {
      id: 12,
      project: "SolarConquest",
      name: "Sunstone",
      price: 0.4,
      image: "https://via.placeholder.com/150/000FF/808080?text=Sunstone",
      category: "Collectible",
      featured: false,
      description: "A rare stone that enhances your abilities.",
    },
  
    // Assets for Vortex Token (VTX)
    {
      id: 13,
      project: "VortexWarriors",
      name: "Vortex Axe",
      price: 0.7,
      image: "https://via.placeholder.com/150/800080/808080?text=Vortex+Axe",
      category: "Weapon",
      featured: true,
      description: "A powerful axe that manipulates space-time.",
    },
    {
      id: 14,
      project: "VortexWarriors",
      name: "Time Cloak",
      price: 1.1,
      image: "https://via.placeholder.com/150/800080/808080?text=Time+Cloak",
      category: "Armor",
      featured: true,
      description: "A cloak that allows you to move through time.",
    },
    {
      id: 15,
      project: "VortexWarriors",
      name: "Eternal Shard",
      price: 0.6,
      image: "https://via.placeholder.com/150/800080/808080?text=Eternal+Shard",
      category: "Collectible",
      featured: false,
      description: "A shard that enhances your abilities.",
    },
  
    // Assets for Nebula Coin (NBH)
    {
      id: 16,
      project: "NebulaHorizon",
      name: "Nebula Staff",
      price: 0.4,
      image: "https://via.placeholder.com/150/000000/808080?text=Nebula+Staff",
      category: "Weapon",
      featured: true,
      description: "A staff that manipulates the cosmos.",
    },
    {
      id: 17,
      project: "NebulaHorizon",
      name: "Astral Armor",
      price: 1.0,
      image: "https://via.placeholder.com/150/000000/808080?text=Astral+Armor",
      category: "Armor",
      featured: false,
      description: "Armor that enhances your connection to the cosmos.",
    },
    {
      id: 18,
      project: "NebulaHorizon",
      name: "Black Hole Crystal",
      price: 0.5,
      image: "https://via.placeholder.com/150/000000/808080?text=Black+Hole+Crystal",
      category: "Collectible",
      featured: true,
      description: "A crystal that enhances your abilities.",
    }
  ];
  